### ISSUE TITLE
Añadir funcion hola mundo

### ISSUE THREAD

**Issue by DNovaO** [SludgyEar/TallerGitMarzo2024#1]
Genere una funcion en python un Hola mundo!
![image](https://github.com/SludgyEar/TallerGitMarzo2024/assets/98285325/2037ede4-46eb-40b2-b962-21d97a2e475a)

**Comment by ZequiVitaAdMortem** [comment]
![424707889_682446447388066_3404985931558062618_n](https://github.com/SludgyEar/TallerGitMarzo2024/assets/94762271/13d8ccb4-4795-4bbb-bb7f-230340d6650b)
